version: '3.7'

services:

  transaction-tracker-web:
    build: ./transaction-tracker-web/.
    image: transaction-tracker-web
    container_name: transaction-tracker-web
    volumes:
      - './transaction-tracker-web:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - transaction-tracker-api

  transaction-tracker-api:
    build: ./transaction-tracker-api/.
    image: transaction-tracker-api
    container_name: transaction-tracker-api
    restart: on-failure
    ports: 
      - 8089:8080
    depends_on:
      - transaction-tracker-database
    healthcheck:
      test: curl --fail -s http://localhost:8089/ || exit 1
      interval: 5s
      timeout: 2s
      retries: 3

  transaction-tracker-database:
    build: ./transaction-tracker-database/MySQL/.
    image: transaction-tracker-database-mysql
    container_name: transaction-tracker-database-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: {}
